# The SimStock match server.
#
# Build from the repository root, not from server/: the server shares sim.js
# with the browser, so the market is generated by the same code on both sides.
#   docker build -t simstock-server .
#   docker run -p 8080:8080 simstock-server
FROM node:22-alpine

WORKDIR /app
ENV NODE_ENV=production

COPY server/package.json server/package-lock.json* ./server/
RUN cd server && npm ci --omit=dev

COPY sim.js ./sim.js
COPY server/server.js ./server/server.js

EXPOSE 8080
USER node
CMD ["node", "server/server.js"]
