// Pulls the game's fonts into fonts/ so it runs with no internet, which a
// desktop build has to. Latin subsets only — the game is in English — and
// identical files are written once, because Google serves one variable font
// for several weights.
//
//   node tools/fetch-fonts.js
const fs = require('fs');
const path = require('path');
const crypto = require('crypto');

const OUT = path.join(__dirname, '..', 'fonts');
const UA = 'Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36';
const SPEC = 'family=IBM+Plex+Mono:wght@400;500;600&family=IBM+Plex+Sans:wght@400;500;600'
  + '&family=Newsreader:ital,opsz,wght@0,6..72,400;0,6..72,500;0,6..72,700;1,6..72,400;1,6..72,500&display=swap';
const KEEP = new Set(['latin', 'latin-ext']);

const get = async url => fetch(url, { headers: { 'User-Agent': UA } });

(async () => {
  fs.rmSync(OUT, { recursive: true, force: true });
  fs.mkdirSync(OUT, { recursive: true });

  const css = await (await get(`https://fonts.googleapis.com/css2?${SPEC}`)).text();
  // One @font-face per subset, each preceded by a /* subset */ comment.
  const parts = css.split(/\/\*\s*([\w-]+)\s*\*\//).slice(1);

  const byHash = new Map();
  let out = '/* The game\'s fonts, kept locally so it works with no internet.\n'
    + '   Generated by tools/fetch-fonts.js — do not edit by hand. */\n\n';
  let faces = 0;

  for (let i = 0; i < parts.length; i += 2) {
    const subset = parts[i];
    const face = parts[i + 1];
    if (!KEEP.has(subset)) continue;
    const url = (face.match(/url\((https:\/\/[^)]+)\)/) || [])[1];
    if (!url) continue;

    const buf = Buffer.from(await (await get(url)).arrayBuffer());
    const hash = crypto.createHash('sha1').update(buf).digest('hex').slice(0, 8);
    let file = byHash.get(hash);
    if (!file) {
      const family = face.match(/font-family:\s*'([^']+)'/)[1].replace(/\s+/g, '');
      const style = (face.match(/font-style:\s*(\w+)/) || [, 'normal'])[1];
      file = `${family}-${style}-${subset}-${hash}.woff2`;
      fs.writeFileSync(path.join(OUT, file), buf);
      byHash.set(hash, file);
    }
    out += `/* ${subset} */\n${face.replace(url, file).trim()}\n\n`;
    faces += 1;
  }

  fs.writeFileSync(path.join(OUT, 'fonts.css'), out);
  const bytes = fs.readdirSync(OUT).reduce((n, f) => n + fs.statSync(path.join(OUT, f)).size, 0);
  console.log(`${faces} faces over ${byHash.size} files, ${(bytes / 1024).toFixed(0)}KB`);
})();
